INSERT INTO BD_BRIND.dbo.VEXTEL(ID_CLIEN, ID_VEND, ID_TELMAR)
SELECT 
	distinct
	CL.ID_CLIEN, 
	VD.ID_VEND,
	TL.ID_TELMAR
FROM BD_BRIND.dbo.CLIEN CL
	JOIN PROD_2023.dbo.ENXES ES ON CL.COD_DMD = ES.Cod_Client
	JOIN BD_BRIND.dbo.VEND VD ON ES.Cod_Vendedor = VD.COD_DMD
	JOIN BD_BRIND.dbo.TELMAR TL ON ES.Cod_Operador = TL.COD_DMD
WHERE Cod_Estabe = 1