USE [BD_BRIND]
GO

/****** Object:  Table [dbo].[NF_CB_SAI]    Script Date: 22/10/2024 13:02:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[NF_CB_SAI](
	[ID_CB_SAI] [int] IDENTITY(1,1) NOT NULL,
	[NUM_PED] [nvarchar](20) NOT NULL,
	[NUM_NOTA] [nvarchar](20) NOT NULL,
	[Dat_Saida] [date] NOT NULL,
	[ID_CLIEN] [int] NOT NULL,
	[Qtd_Total] [int] NOT NULL,	
	[Obs] [text] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_CB_SAI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


