CREATE TABLE CIDADE (
    [ID_CIDADE] INT IDENTITY(1,1) NOT NULL,
    [ID_ESTADO] [INT] NOT NULL,
    [NOME] VARCHAR (80),
    [IBGE_CID] NUMERIC

PRIMARY KEY CLUSTERED 
(
	[ID_CIDADE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO