CREATE TABLE ENTXEND (
    [ID_ENT] int IDENTITY(1,1) NOT NULL,
    [ID_FORN] [INT] NOT NULL,
    [ID_CLIEN] [INT] NOT NULL,
    [TEL] [VARCHAR] (11) NULL,
    [ID_LOG] [INT] NULL,
    [ID_WEB] [INT] NULL
PRIMARY KEY CLUSTERED 
(
	[ID_ENT] ASC
))