CREATE TABLE ESTADO (
    [ID_CIDADE] INT IDENTITY(1,1) NOT NULL,
    [UF] [VARCHAR](2) NOT NULL,
    [DESCRICAO] VARCHAR (80),
    [IBGE_EST] NUMERIC
PRIMARY KEY CLUSTERED 
(
	[ID_CIDADE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO