USE [BD_BRIND]
GO

/****** Object:  Table [dbo].[FORNE]    Script Date: 16/10/2024 18:39:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FORNE](
	[IdFornecedor] [int] IDENTITY(1,1) NOT NULL,
	[Fantasia] [nvarchar](100) NOT NULL,
	[CNPJ_FORN] [char](14) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IdFornecedor] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


