CREATE TABLE [dbo].[FORNE](
	[ID_FORNE] [int] IDENTITY(1,1) NOT NULL,
	[Razao_Social] [varchar](100) NOT NULL,
	[CNPJ_FORN] [varchar](20) NOT NULL,
	[Tip_Comp] [bit] NULL,
	[ID_ENTXEND] [int] NULL
PRIMARY KEY CLUSTERED 
(
	[ID_FORNE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO