USE [BD_BRIND]
GO

/****** Object:  Table [dbo].[NF_CB_SAI]    Script Date: 16/10/2024 18:41:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[NF_CB_SAI](
	[IdNota_Sai] [int] IDENTITY(1,1) NOT NULL,
	[NF_SAI] [nvarchar](20) NOT NULL,
	[Dat_Saida] [date] NOT NULL,
	[Qtd_Total] [int] NOT NULL,
	[Cod_Pedido] [nvarchar](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IdNota_Sai] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


