
CREATE TABLE [dbo].[PDVCB](
	[Numero] [int] NOT NULL,
	[Tip_Pedido] [varchar](1) NULL,
	[Status1] [varchar](1) NULL,
	[Status2] [varchar](1) NULL,
	[Bloqueio] [varchar](2) NULL,
	[Flg_JaFechado] [bit] NULL,
	[Flg_Calc] [bit] NOT NULL,
	[Qtd_ImpPnt] [int] NULL,
	[Cod_OrigemPdv] [varchar](2) NULL,
	[Cod_PedRem] [int] NULL,
	[Cod_PedCli] [varchar](20) NULL,
	[Flg_ComisNormal] [bit] NULL,
	[Per_ComVnd] [numeric](18, 8) NULL,
	[Flg_TabProgres] [bit] NULL,
	[Tip_Faturamento] [varchar](3) NULL,
	[Tip_Vencimento] [varchar](1) NULL,
	[Dat_Pedido] [smalldatetime] NULL,
	[Cod_SerNfs] [varchar](3) NULL,
	[Cod_NumNfsIni] [int] NULL,
	[Cod_NumNfsFim] [int] NULL,
	[Cod_Cliente] [int] NULL,
	[Cod_Funcionario] [int] NULL,
	[Num_Lote] [int] NULL,
	[Consumidor] [varchar](35) NULL,
	[Tip_Consumidor] [varchar](1) NULL,
	[Qtd_PrzMed] [numeric](18, 8) NULL,
	[Qtd_Parcela] [int] NULL,
	[Qtd_Intervalo] [int] NULL,
	[Flg_PrzProm] [bit] NULL,
	[Flg_VlrFinanc] [bit] NULL,
	[Cod_VendTlmkt] [int] NULL,
	[Cod_Vendedor] [int] NULL,
	[Cod_Agente] [int] NULL,
	[Cod_Transportadora] [int] NULL,
	[Cod_Rota] [int] NULL,
	[Cod_MicroReg] [int] NULL,
	[Cod_RegTri] [int] NULL,
	[Qtd_Itens] [int] NULL,
	[Qtd_ItensProm] [int] NULL,
	[Vlr_BasDscCom] [numeric](18, 8) NULL,
	[Vlr_BasPar] [numeric](18, 8) NULL,
	[Vlr_LiqItens] [numeric](18, 8) NULL,
	[Vlr_RepIcms] [numeric](18, 8) NULL,
	[Vlr_SubsTrib] [numeric](18, 8) NULL,
	[Vlr_DscTri] [numeric](18, 8) NULL,
	[Tip_DscPdv] [varchar](1) NULL,
	[Per_DescontoCom] [numeric](18, 8) NULL,
	[Per_DescontoFin] [numeric](18, 8) NULL,
	[C_VlrDesconto] [numeric](18, 8) NULL,
	[C_VlrPedido] [numeric](18, 8) NULL,
	[Observacao] [text] NULL,
	[Qtd_Volumes] [int] NULL,
	[Qtd_Peso] [numeric](18, 8) NULL,
	[Hor_Entrada] [smalldatetime] NULL,
	[Hor_Prenota] [smalldatetime] NULL,
	[Hor_Fatura] [smalldatetime] NULL,
	[Hor_Saida] [smalldatetime] NULL,
	[Cod_FunSeparador] [int] NULL,
	[Cod_FunConferidor] [int] NULL,
	[Cod_FunEmbalador] [int] NULL,
	[Flg_Credito] [int] NULL,
	[Msg_Bloqueio] [varchar](30) NULL,
	[Msg_NF] [varchar](50) NULL,
	[Nom_UsuDesbloq] [varchar](15) NULL,
	[Msg_JustDesbloq] [varchar](50) NULL,
	[Cod_Propos] [int] NULL,
	[Per_SubFat] [numeric](18, 8) NULL,
	[Usuario] [varchar](15) NULL,
	[Transacao] [smalldatetime] NULL,
	[Per_DsdOrc] [numeric](18, 0) NULL,
	[Cod_Prz] [int] NULL,
	[Hor_ConferIni] [smalldatetime] NULL,
	[Hor_ConferFim] [smalldatetime] NULL,
	[Cod_Digitador] [int] NULL,
	[Cod_GrpCli] [int] NULL,
	[Per_DscPrz] [numeric](18, 4) NULL,
	[Per_DscVis] [numeric](18, 4) NULL,
	[Qtd_Prz] [int] NULL,
	[Cod_TabPrc] [int] NULL,
	[Num_Referencia] [int] NULL,
	[Flg_GerArqNf] [bit] NULL,
	[Obs_NotFis] [text] NULL,
	[Cod_TipPrp] [varchar](3) NULL,
	[Obs_IntCtaRec] [text] NULL,
	[Num_CotPdv] [int] NULL,
	[Per_Rnt] [numeric](18, 4) NULL,
	[Cod_BlqRnt] [char](1) NULL,
	[Nom_UsuDesbloqRnt] [varchar](15) NULL,
	[Des_LayoutPalm] [varchar](16) NULL,
	[Flg_WMS] [bit] NULL,
	[Flg_CalCom] [bit] NULL,
	[Vlr_Comissao] [numeric](18, 4) NULL,
	[Vlr_ComTlmkt] [numeric](18, 4) NULL,
	[Val_ComTra] [numeric](18, 4) NULL,
	[Cod_BlqLic] [char](1) NULL,
	[Nom_UsuDesbloqLic] [varchar](15) NULL,
	[Num_ConReg] [int] NULL,
	[Est_ConReg] [varchar](2) NULL,
	[Ide_NotEmp] [varchar](20) NULL,
	[Per_ComOpe] [numeric](18, 4) NULL,
	[Qtd_PesBru] [numeric](18, 4) NULL,
	[Hor_Fechamento] [smalldatetime] NULL,
	[Hor_Liberacao] [smalldatetime] NULL,
	[Hor_DbqFin] [smalldatetime] NULL,
	[Hor_DbqLic] [smalldatetime] NULL,
	[Hor_DbqRnt] [smalldatetime] NULL,
	[Dat_LimEnvPrp] [smalldatetime] NULL,
	[Vlr_Frete] [numeric](18, 4) NULL,
	[Cod_PolCom] [varchar](25) NULL,
	[Id_PolCom] [int] NULL,
	[Vlr_Verba] [numeric](18, 4) NULL,
	[Ide_Contra] [varchar](40) NULL,
	[Cod_Contrato] [int] NULL,
	[Num_SequenciaCtr] [int] NULL,
	[Flg_GerCtrFal] [bit] NULL,
	[Flg_CriIteFec] [bit] NULL,
	[Hor_Cancel] [smalldatetime] NULL,
	[Nom_UsuCancel] [varchar](15) NULL,
	[Msg_JustCancel] [varchar](80) NULL,
	[Vlr_FrePrv] [numeric](18, 4) NULL,
	[Flg_GerPdvBon] [bit] NULL,
	[Num_PdvLig] [int] NULL,
	[Cod_MtvRej] [varchar](3) NULL,
	[Des_MtvRej] [varchar](40) NULL,
	[Per_FrePrv] [numeric](18, 4) NULL,
	[Cod_Gerencia] [int] NULL,
	[Per_ComGer] [numeric](18, 4) NULL,
	[Vlr_ComGer] [numeric](18, 4) NULL,
	[Cod_Supervisor] [int] NULL,
	[Per_ComSup] [numeric](18, 4) NULL,
	[Vlr_ComSup] [numeric](18, 4) NULL,
	[Cod_GerOpe] [int] NULL,
	[Per_ComGerOpe] [numeric](18, 4) NULL,
	[Vlr_ComGerOpe] [numeric](18, 4) NULL,
	[Cod_SupOpe] [int] NULL,
	[Per_ComSupOpe] [numeric](18, 4) NULL,
	[Vlr_ComSupOpe] [numeric](18, 4) NULL,
	[Vlr_VrbPar] [numeric](18, 4) NULL,
	[Vlr_VrbBon] [numeric](18, 4) NULL,
	[Des_LayoutPde] [varchar](25) NULL,
	[Flg_GerRetBon] [bit] NULL,
	[Des_Convenio] [varchar](30) NULL,
	[UF_PlaVei] [varchar](2) NULL,
	[Cod_PlaVei] [varchar](10) NULL,
	[Flg_PriFat] [bit] NULL,
	[Cod_PrjPde] [varchar](12) NULL,
	[Hor_ImpEtq] [smalldatetime] NULL,
	[Num_PrtOri] [int] NULL,
	[Vlr_SbtRes] [numeric](18, 8) NULL,
	[Tip_SaiPdv] [varchar](1) NULL,
	[Flg_MarkupCusCom] [bit] NULL,
	[Vlr_DscBon] [numeric](18, 4) NULL,
	[Ide_NumPregao] [varchar](20) NULL,
	[CodAnt] [int] NULL,
	[NovoCodigo] [int] NULL,
	[Cod_PedCmpCli] [varchar](20) NULL,
	[Flg_CnvDscIteDscGlb] [bit] NULL,
	[Cod_Estabe] [int] NOT NULL,
	[Cod_LayoutPde] [int] NULL,
	[Tip_RatBon] [varchar](1) NULL,
	[Vlr_IcmFcpDes] [numeric](18, 4) NULL,
	[Vlr_Despes] [numeric](18, 4) NULL,
	[Vlr_IcmParDes] [numeric](18, 4) NULL,
	[Vlr_IcmParRem] [numeric](18, 4) NULL,
	[Flg_UsaPbm] [bit] NULL,
	[Obs_IntFecPdv] [text] NULL,
	[Num_PdvPai] [int] NULL,
	[Num_PdvFilho] [int] NULL,
	[Per_MarBru] [numeric](18, 4) NULL,
	[Per_RntBru] [numeric](18, 4) NULL,
	[Cod_RamAtv] [int] NULL,
	[Vlr_DscBonDup] [numeric](18, 4) NULL,
	[Sta_IntWms] [varchar](1) NULL,
	[Cod_MtvDbq] [varchar](6) NULL,
	[Flg_CtrUsuPdv] [bit] NULL,
	[Inscricao_Suframa] [varchar](9) NULL,
	[Vlr_IcmsDeson] [numeric](18, 4) NOT NULL,
	[Vlr_DscCalSuframa] [numeric](18, 4) NOT NULL,
	[Obs_Padrao] [text] NULL,
	[Tip_Frete] [varchar](1) NULL,
	[Tip_GerVrb] [varchar](1) NULL,
	[Vlr_VrbVdr] [numeric](18, 4) NULL,
	[Vlr_VrbOpe] [numeric](18, 4) NULL,
	[Vlr_VrbSup] [numeric](18, 4) NULL,
	[Sta_SepLot] [varchar](1) NULL,
	[Flg_BlqDebVrbNotBon] [bit] NULL,
	[Id_Consig] [int] NULL,
	[Num_SeqDev] [smallint] NULL,
	[Id_IncFis] [smallint] NULL,
	[Vlr_DspExt] [numeric](18, 4) NULL,
	[Vlr_Ipi] [numeric](18, 4) NULL,
	[Flg_AltUnvItePdv] [bit] NULL,
	[Vlr_BasIrf] [numeric](18, 4) NULL,
	[Vlr_Irf] [numeric](18, 4) NULL,
	[ID_PVMCB] [int] NULL,
	[Vlr_BasCsl] [numeric](18, 4) NULL,
	[Vlr_Csl] [numeric](18, 4) NULL,
 CONSTRAINT [PK_PDVCB] PRIMARY KEY CLUSTERED 
(
	[Cod_Estabe] ASC,
	[Numero] ASC
)) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


