
CREATE TABLE [dbo].[PDVIT](
	[Cod_Pedido] [int] NOT NULL,
	[Cod_Produto] [int] NOT NULL,
	[Cod_Lote] [varchar](20) NOT NULL,
	[Cod_Fabricante] [int] NULL,
	[Loc_Fisica] [varchar](15) NULL,
	[Qtd_Solicitado] [int] NULL,
	[Qtd_Acerto] [int] NULL,
	[Qtd_Pedido] [int] NULL,
	[Qtd_Bonificacao] [int] NULL,
	[Qtd_Pendente] [int] NULL,
	[Flg_PrcUniDsc] [bit] NULL,
	[Per_Desconto] [numeric](18, 8) NULL,
	[Prc_Unitario] [numeric](18, 8) NULL,
	[Tip_Aux] [varchar](1) NULL,
	[Ctrl_Tributacao] [varchar](2) NULL,
	[Cod_ClaTri] [varchar](4) NULL,
	[Alq_Icms] [numeric](18, 8) NULL,
	[Vlr_BasIcmsNor] [numeric](18, 8) NULL,
	[Vlr_IcmsNor] [numeric](18, 8) NULL,
	[Vlr_RepIcms] [numeric](18, 8) NULL,
	[Vlr_BasRepIcms] [numeric](18, 8) NULL,
	[Vlr_SubsTrib] [numeric](18, 8) NULL,
	[Vlr_PrdSubTri] [numeric](18, 8) NULL,
	[Vlr_BasSubsTrib] [numeric](18, 8) NULL,
	[Vlr_IcmsTri] [numeric](18, 8) NULL,
	[Vlr_BasIcmsTri] [numeric](18, 8) NULL,
	[Vlr_Isento] [numeric](18, 8) NULL,
	[Vlr_DscTri] [numeric](18, 8) NULL,
	[Vlr_Bruto] [numeric](18, 8) NULL,
	[Cod_Promocao] [int] NULL,
	[Desconto] [bit] NULL,
	[Flg_BlqInfPar] [bit] NULL,
	[Qtd_PrzMax] [int] NULL,
	[Per_Descon] [numeric](18, 8) NULL,
	[Per_DscVis] [numeric](18, 8) NULL,
	[C_VlrDesconto] [numeric](18, 4) NULL,
	[C_PrcUni] [numeric](18, 8) NULL,
	[C_PerDscIte] [numeric](18, 4) NULL,
	[C_PrcTotal] [numeric](18, 4) NULL,
	[C_VlrLiquido] [numeric](18, 4) NULL,
	[Prc_Tabela] [numeric](18, 4) NULL,
	[Des_Und] [varchar](3) NULL,
	[Qtd_AprPdv] [int] NULL,
	[Des_UndVen] [varchar](12) NULL,
	[Prc_TabBru] [numeric](18, 4) NULL,
	[Vlr_Outros] [numeric](18, 4) NULL,
	[Flg_Entreg] [bit] NULL,
	[Qtd_ImpFat] [numeric](18, 4) NULL,
	[Prc_UniImpFat] [numeric](18, 8) NULL,
	[Fat_CnvImpFat] [int] NULL,
	[Qtd_Pra] [int] NULL,
	[Qtd_Dep] [int] NULL,
	[Prc_MaxCon] [numeric](18, 4) NULL,
	[Prc_Fabric] [numeric](18, 4) NULL,
	[Num_SeqDig] [int] NULL,
	[Nom_UsuDesbloq] [varchar](15) NULL,
	[Des_UnvImpFat] [char](3) NULL,
	[Des_AprImpFat] [varchar](12) NULL,
	[Flg_VctLic] [bit] NULL,
	[Per_Rnt] [numeric](18, 4) NULL,
	[Prc_BasRnt] [numeric](18, 4) NULL,
	[Per_Comissao] [numeric](18, 4) NULL,
	[Per_ComTlmkt] [numeric](18, 4) NULL,
	[Per_ComTra] [numeric](18, 4) NULL,
	[Vlr_Comissao] [numeric](18, 4) NULL,
	[Vlr_ComTlmkt] [numeric](18, 4) NULL,
	[Val_ComTra] [numeric](18, 4) NULL,
	[Cod_ModBasCalIcm] [char](1) NULL,
	[Cod_ModBasCalIcmSbt] [char](1) NULL,
	[Per_RedBasCalIcm] [numeric](18, 4) NULL,
	[Per_RedBasCalIcmSbt] [numeric](18, 4) NULL,
	[Alq_IcmSbt] [numeric](18, 4) NULL,
	[Vlr_BasTri] [numeric](18, 8) NULL,
	[Alq_AgrSbt] [numeric](18, 4) NULL,
	[Id_PolCom] [int] NULL,
	[Flg_Verba] [bit] NULL,
	[Prc_PolCom] [numeric](18, 8) NULL,
	[Per_DscPolCom] [numeric](18, 4) NULL,
	[Per_DscVisPolCom] [numeric](18, 4) NULL,
	[Vlr_Verba] [numeric](18, 4) NULL,
	[Qtd_PrzPolCom] [int] NULL,
	[Des_MsgDesbloq] [varchar](60) NULL,
	[Prc_UniLiqPer] [numeric](18, 8) NULL,
	[Prc_LiqUltEnt] [numeric](18, 8) NULL,
	[Cod_MtvRej] [varchar](3) NULL,
	[Des_MtvRej] [varchar](80) NULL,
	[Per_ComGer] [numeric](18, 4) NULL,
	[Vlr_ComGer] [numeric](18, 4) NULL,
	[Per_ComSup] [numeric](18, 4) NULL,
	[Vlr_ComSup] [numeric](18, 4) NULL,
	[Per_ComGerOpe] [numeric](18, 4) NULL,
	[Vlr_ComGerOpe] [numeric](18, 4) NULL,
	[Per_ComSupOpe] [numeric](18, 4) NULL,
	[Vlr_ComSupOpe] [numeric](18, 4) NULL,
	[Per_VrbPar] [numeric](18, 4) NULL,
	[Vlr_VrbPar] [numeric](18, 4) NULL,
	[Per_VrbBon] [numeric](18, 4) NULL,
	[Vlr_VrbBon] [numeric](18, 4) NULL,
	[Prc_UniPde] [numeric](18, 4) NULL,
	[Per_DscPde] [numeric](18, 4) NULL,
	[Prc_RefFpb] [numeric](18, 4) NULL,
	[Cod_CSOSN] [varchar](3) NULL,
	[Flg_PolPrm] [bit] NULL,
	[Cod_PrjPde] [varchar](12) NULL,
	[Num_SeqPdc] [varchar](6) NULL,
	[Vlr_BasSbtRes] [numeric](18, 8) NULL,
	[Vlr_SbtRes] [numeric](18, 8) NULL,
	[Num_IteCot] [varchar](6) NULL,
	[Vlr_Bonificacao] [numeric](18, 4) NULL,
	[Vlr_DscBonRat] [numeric](18, 4) NULL,
	[Prc_CusMinComMarkup] [numeric](18, 4) NULL,
	[Vlr_BasVerba] [numeric](18, 4) NULL,
	[Vlr_VrbVdr] [numeric](18, 4) NULL,
	[Per_MarkupCusCom] [numeric](18, 4) NULL,
	[Tip_Sai] [varchar](1) NOT NULL,
	[CodAnt] [int] NULL,
	[NovoCodigo] [int] NULL,
	[Cod_Estabe] [int] NOT NULL,
	[Per_AcrAlqIntFcp] [numeric](18, 4) NULL,
	[Vlr_IcmFcpDes] [numeric](18, 4) NULL,
	[Vlr_Despes] [numeric](18, 4) NULL,
	[Vlr_BasDespes] [numeric](18, 4) NULL,
	[Per_PrvParIcm] [numeric](18, 4) NULL,
	[Vlr_IcmParDes] [numeric](18, 4) NULL,
	[Vlr_IcmParRem] [numeric](18, 4) NULL,
	[Alq_IntIcmDes] [numeric](18, 4) NULL,
	[Cod_KitPrm] [int] NULL,
	[CST_Pis] [varchar](2) NULL,
	[Vlr_BasPis] [numeric](18, 4) NULL,
	[Alq_Pis] [numeric](18, 4) NULL,
	[Vlr_Pis] [numeric](18, 4) NULL,
	[CST_Cofins] [varchar](2) NULL,
	[Vlr_BasCofins] [numeric](18, 4) NULL,
	[Alq_Cofins] [numeric](18, 4) NULL,
	[Vlr_Cofins] [numeric](18, 4) NULL,
	[Per_MarBru] [numeric](18, 4) NULL,
	[Vlr_VrbPdv] [numeric](18, 4) NULL,
	[Vlr_BasCalSubTriEntMed] [numeric](18, 4) NULL,
	[Per_RntBru] [numeric](18, 4) NULL,
	[Tip_BasRnt] [varchar](1) NULL,
	[Flg_UsaDebPresum] [bit] NULL,
	[Alq_IcmPresum] [numeric](18, 4) NULL,
	[Vlr_DscBonDup] [numeric](18, 4) NULL,
	[Vlr_BasDscTri] [numeric](18, 4) NULL,
	[Per_DscTri] [numeric](9, 4) NULL,
	[Alq_IcmDif] [numeric](9, 4) NULL,
	[Vlr_IcmsDif] [numeric](18, 4) NULL,
	[Qtd_PesVolImpFat] [numeric](18, 4) NOT NULL,
	[Des_UnvPesVolImpFat] [varchar](3) NULL,
	[Prc_UniPesVolImpFat] [numeric](18, 8) NOT NULL,
	[Vlr_IcmsDeson] [numeric](18, 4) NOT NULL,
	[Cod_MtvIcmsDeson] [varchar](2) NULL,
	[Vlr_DscCalSuframa] [numeric](18, 4) NOT NULL,
	[Flg_IncFis] [bit] NOT NULL,
	[Alq_FcpIcm] [numeric](18, 4) NULL,
	[Vlr_FcpIcm] [numeric](18, 4) NULL,
	[Alq_FcpSbt] [numeric](18, 4) NULL,
	[Vlr_FcpSbt] [numeric](18, 4) NULL,
	[Alq_FcpSbtRet] [numeric](18, 4) NULL,
	[Vlr_FcpSbtRet] [numeric](18, 4) NULL,
	[Per_IcmDiferi] [numeric](8, 4) NOT NULL,
	[Vlr_IcmDiferi] [numeric](18, 4) NOT NULL,
	[Nom_UsuCor] [varchar](15) NULL,
	[Dat_UsuCor] [datetime] NULL,
	[Cod_MtvCor] [varchar](3) NULL,
	[Des_MtvCor] [varchar](40) NULL,
	[Vlr_VrbOpe] [numeric](18, 4) NULL,
	[Vlr_VrbSup] [numeric](18, 4) NULL,
	[Per_VrbVdr] [numeric](5, 2) NULL,
	[Per_VrbOpe] [numeric](5, 2) NULL,
	[Per_VrbSup] [numeric](5, 2) NULL,
	[Alq_EfeDas] [numeric](7, 4) NULL,
	[Vlr_DscRat] [numeric](18, 4) NULL,
	[Prc_PonFin] [numeric](18, 4) NULL,
	[Vlr_DspExt] [numeric](18, 4) NULL,
	[Vlr_BasIpi] [numeric](18, 4) NULL,
	[Vlr_Ipi] [numeric](18, 4) NULL,
	[Alq_Ipi] [numeric](7, 4) NULL,
	[CST_Ipi] [varchar](2) NULL,
	[Cod_EnqIpi] [varchar](3) NULL,
	[Cod_OriMer] [varchar](3) NULL,
	[Prc_UniSemAcrIcm] [numeric](18, 8) NULL,
	[Flg_PrcUniAcrIcm] [bit] NULL,
	[Prc_UniComAcrIcm] [numeric](18, 8) NULL,
	[Per_RepIcms] [numeric](7, 4) NULL,
	[Vlr_BasIrf] [numeric](18, 4) NULL,
	[Alq_Irf] [numeric](18, 4) NULL,
	[Vlr_Irf] [numeric](18, 4) NULL,
	[Qtd_GanCot] [int] NULL,
	[Per_LinCot] [numeric](8, 4) NULL,
	[Vlr_SbtRetAnt] [numeric](18, 4) NULL,
	[Vlr_BasCsl] [numeric](18, 4) NULL,
	[Alq_Csl] [numeric](7, 4) NULL,
	[Vlr_Csl] [numeric](18, 4) NULL,
	[Tip_PolCom] [varchar](4) NULL,
 CONSTRAINT [PK_PDVIT] PRIMARY KEY CLUSTERED 
(
	[Cod_Estabe] ASC,
	[Cod_Pedido] ASC,
	[Cod_Produto] ASC,
	[Cod_Lote] ASC,
	[Tip_Sai] ASC
)) 
