USE [BD_BRIND]
GO

/****** Object:  Table [dbo].[PROD]    Script Date: 16/10/2024 18:42:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PROD](
	[IdProduto] [int] IDENTITY(1,1) NOT NULL,
	[Descricao] [nvarchar](100) NOT NULL,
	[EAN] [char](13) NOT NULL,
	[IdForne] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdProduto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PROD]  WITH CHECK ADD FOREIGN KEY([IdForne])
REFERENCES [dbo].[FORNE] ([IdFornecedor])
GO


