USE [BD_BRIND]
GO

/****** Object:  Table [dbo].[VEND]    Script Date: 16/10/2024 18:42:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[VEND](
	[IdVend] [int] IDENTITY(1,1) NOT NULL,
	[Nome_Guerra] [nvarchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IdVend] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


